matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk13

  allow_failures:
    - jdk: openjdk13
    
language: java

sudo: false # faster builds

script: "mvn clean package"

git:
  depth: 3
